# Site
name: "Fusion Autonomy"
title: "Fusion Autonomy"
description: "FusionAutonomy Group @ WPI"
meta_description: "FusionAutonomy Group @ WPI"
logo: 'assets/images/wpi_logo_m.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'FusionAutonomous Group @ WPI'
google_analytics: 'UA-46278016-1'
disqus: 'officialweb'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
author:
  lbai:
    name: Lin
    display_name: Lin
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: lbai.ece.wpi@gmail.com
    web: https://linbaiwpi.github.io
    description: "PhD Candidate of ECE WPI"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
